version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_DEV_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}
      POSTGRES_DB: ${DATABASE_DEV_DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data
